# Generated by Django 3.2.5 on 2021-08-18 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code_name', models.CharField(default='', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 8, 18, 10, 59, 39, 142460, tzinfo=utc))),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(default='', max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('news_body', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=150)),
                ('video_url', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 8, 18, 10, 59, 39, 145025, tzinfo=utc))),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='news_category', to='api.category')),
                ('comments', models.ManyToManyField(blank=True, default='', related_name='news_comment', to='api.Comment')),
            ],
        ),
    ]
